
--Insert into DEPARTMENT_DETAILS (ID,NAME) VALUES (10,'Accounts');
--Insert into DEPARTMENT_DETAILS (ID,NAME) VALUES (11,'HR');

--Insert into ROLE_DETAILS (ID,NAME) VALUES (10001,'Admin');
--Insert into ROLE_DETAILS (ID,NAME) VALUES (10002,'User');

--Insert into EMPLOYEE_DETAILS (ID,NAME,DEPARTMENT_ID) values (1001,'Ramesh', 10);
--Insert into EMPLOYEE_DETAILS (ID,NAME, DEPARTMENT_ID) values (1002,'Makesh', 11);

--Insert into EMPLOYEE_ROLE (EMPLOYEE_ID,ROLE_ID) VALUES (1001,10001);
--Insert into EMPLOYEE_ROLE (EMPLOYEE_ID,ROLE_ID) VALUES (1001,10002);
--Insert into EMPLOYEE_ROLE (EMPLOYEE_ID,ROLE_ID) VALUES (1002,10002);

--Insert into ADDRESS_DETAILS (ID,CITY,PINCODE,STATE,STREET,EMPLOYEE_ID) VALUES (100,'BAngalore',560017,'Karnataka','HAL',1001);
--Insert into ADDRESS_DETAILS (ID,CITY,PINCODE,STATE,STREET,EMPLOYEE_ID) VALUES (101,'Bangalore',560013,'Karnataka','Ambalipura village',1001);

--Insert into ADDRESS_DETAILS (ID,CITY,PINCODE,STATE,STREET,EMPLOYEE_ID) VALUES (103,'BAngalore',560017,'Karnataka','HAL',1002);
--Insert into ADDRESS_DETAILS (ID,CITY,PINCODE,STATE,STREET,EMPLOYEE_ID) VALUES (104,'Bangalore',560013,'Karnataka','Ambalipura village',1002);
--Insert into ADDRESS_DETAILS (ID,CITY,PINCODE,STATE,STREET,EMPLOYEE_ID) VALUES (105,'Bangalore',560023,'Karnataka','Domlur',1002);

